version: '3.5'

services:
  cadvisor:
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    networks:
      - private
      - public
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
      labels:
        - traefik.enable=true
        - traefik.http.routers.cadvisor.rule=PathPrefix(`/cadvisor`)
        - traefik.http.services.cadvisor.loadbalancer.server.port=8080
        - traefik.docker.network=public

  node-exporter:
    image: ruanbekker/node-exporter:v0.18.0
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /etc/hostname:/etc/host_hostname
      - /etc/hostname:/etc/nodename
    ports:
      - 9100:9100
    environment:
      - HOST_HOSTNAME=/etc/host_hostname
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points'
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
      - '--collector.textfile.directory=/etc/node-exporter/'
    networks:
      - private
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
#      labels:
#        - traefik.enable=true
#        - traefik.http.services.alertmanager.loadbalancer.server.port=9100

  blackbox-exporter:
    image: prom/blackbox-exporter:v0.12.0
    networks:
      - private
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 64M

  alertmanager:
    image: prom/alertmanager:v0.17.0
    configs:
      - source: alertmanager_config
        target: /etc/alertmanager/config.yml
      - source: basicauth_htpasswd
        target: /etc/htpasswd
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    volumes:
      - alertmanager:/alertmanager
    networks:
      - private
      - public
    deploy:
      replicas: 1
      placement:
        constraints:
           - node.role==manager
      resources:
        limits:
          memory: 100M
      labels:
        - traefik.enable=true
        - traefik.http.routers.alertmanager.rule=PathPrefix(`/alertmanager`)
        - traefik.http.services.alertmanager.loadbalancer.server.port=9093
        - traefik.docker.network=public
        - traefik.frontend.auth.basic.usersFile=/etc/htpasswd

  prometheus:
    image: prom/prometheus:v2.9.2
    user: root
    volumes:
      - promconfig:/etc/prometheus
      - promdata:/prometheus
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yaml
      - source: prometheus_rules
        target: /etc/prometheus/alert.rules
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
    networks:
      - private
      - public
    deploy:
      placement:
        constraints:
          - node.role==manager
      resources:
        limits:
          memory: 500M
      labels:
        - traefik.enable=true
#        - traefik.http.routers.prometheus.rule=PathPrefix(`/prom`)
        - "traefik.http.routers.prometheus.rule=Host(`prometheus.${DOMAIN:-localhost}`)"
        - traefik.docker.network=public
        - traefik.http.services.prometheus.loadbalancer.server.port=9090

  pushgateway:
    image: prom/pushgateway:v0.8.0
    networks:
      - private
      - public
    configs:
      - source: basicauth_htpasswd
        target: /etc/htpasswd
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==manager
      resources:
        limits:
          memory: 64M
      labels:
        - traefik.enable=true
        - traefik.http.routers.pushgateway.rule=PathPrefix(`/pushgateway`)
        - traefik.http.services.pushgateway.loadbalancer.server.port=9091
        - traefik.docker.network=public
        - traefik.frontend.auth.basic.usersFile=/etc/htpasswd

  grafana:
    image: grafana/grafana:6.2.1
    volumes:
      - grafanadata:/var/lib/grafana
    environment:
      - GF_SERVER_ROOT_URL=http://grafana.${DOMAIN:-localhost}
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
      - PROMETHEUS_ENDPOINT=http://prometheus:9090
    networks:
      - private
      - public
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==manager
      resources:
        limits:
          memory: 384M
      labels:
        - traefik.enable=true
#        - traefik.http.routers.grafana.rule=PathPrefix(`/grafana`)
        - traefik.docker.network=public
        - "traefik.http.routers.grafana.rule=Host(`grafana.${DOMAIN:-localhost}`)"
        - traefik.http.services.grafana.loadbalancer.server.port=3000

networks:
  private:
    name: private
    driver: overlay
  public:
    name: public
    external: true

volumes:
  promconfig: {}
  promdata: {}
  grafanadata: {}
  alertmanager: {}

configs:
  alertmanager_config:
    file: ./alertmanager/configs/alertmanager.yml
  prometheus_config:
    file: ./prometheus/configs/prometheus.yaml
  prometheus_rules:
    file: ./prometheus/rules/alert.rules
  basicauth_htpasswd:
    file: ./htpasswd
